version: '3.8'

services:
  nginx:
    image: nginx:1.25
    container_name: nginx
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 "src.api.app:app"
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - resume-website

networks:
  my-network: